### ISSUE TITLE
Unrunnable qemu cuz lacking of dynamic lib.

### ISSUE THREAD

**Issue by Xanbert** [LoongsonLab/2k1000-materials#1]
Please provide source code for compiling, avoiding lack of dynamic library. Or provide environment running qemu or a static linked qemu.

**Comment by foxsen** [comment]
For statical version, please refer to https://github.com/LoongsonLab/2k1000-materials/releases/download/qemu-static-20240401/qemu-static-20240401.tar.xz. 
As for the source code, this is built from an internal version which I have not got permission to publish. I plan to find some time to port 2k1000 support code to upstream version(It is now based on qemu v3.1)

**Comment by Xanbert** [comment]
> For statical version, please refer to https://github.com/LoongsonLab/2k1000-materials/releases/download/qemu-static-20240401/qemu-static-20240401.tar.xz. As for the source code, this is built from an internal version which I have not got permission to publish. I plan to find some time to port 2k1000 support code to upstream version(It is now based on qemu v3.1)

thx.
